* Intro

This is a collection of files that I use to configure Emacs according to my needs and tastes.\\
I strive to keep it as *minimalistic* and *well-documented* as
possible, so it may bring some insight to a fresh Emacs user.\\
See also [[https://github.com/caisah/emacs.dz][this list of other configurations and starter-kits]] for a source of inspiration.

* Getting Started on Mac

Based on Emacs 26.3 and Emacs 27.1 available at [[https://emacsformacosx.com][EmacsForMacOSX]].


** Install

~$ brew cask install emacs~

This command is sufficient to get a working Emacs application.\\
With such install, Emacs works basically the same way as other applications work, responding to key presses most of the users are used to.\\
For example:
  - quitting Emacs with =Cmd-q= or hiding with =Cmd-h=,
  - making basic text navigation with the =arrows=,
  - editing with =Cmd-c=, =Cmd-v=, =Cmd-a=, =Cmd-x=.

[[https://www.emacswiki.org/emacs/EmacsForMacOS][More on Mac OS installers]].

- Upgrade: ~$ brew upgrade homebrew/cask/emacs~

- Info: ~$ brew cask info homebrew/cask/emacs~

And by the way, Emacs usage is smooth with /Dvorak/ layout and a /split keyboard/.\\
I use [[https://kinesis-ergo.com/shop/advantage2/][Kinesis Advantage]] and have a set of modifier keys [[https://gitlab.com/-/snippets/1744636][under each of my hands]].


** What's Next

As the next step, I highly recommend:
  - following the /Emacs tutorial/ (~Ctrl-h t~),
  - then reading the /Emacs manual/ (~Ctrl-h r~).
I also found [[https://www.emacswiki.org/emacs/EmacsNewbie][EmacsWiki]] to be the most helpful resource online.

Experiment while reading documentation. Be patient!\\
For example, it took me two months to read the manual and get comfortable with Emacs.\\
To that moment I wrote the simplest possible [[https://github.com/yugaego/emacs-config/blob/bare-bones/init.el][configuration file]] that matched my tastes and built [[https://github.com/yugaego/cheat-sheets/blob/main/Emacs.org][this key bindings cheat sheet]].


* Playing With This Repo

** Install

- One, clone this configuration:
  - Backup contents of the directory =~/.emacs.d=, if you have the one.
  - ~$ git clone git@gitlab.com:yugaego/emacs-config.git ~/.emacs.d~
  - or ~$ git clone git@github.com:yugaego/emacs-config.git ~/.emacs.d~

- Two, install configured packages:
  - Open =install-packages.el= in Emacs.
  - Execute command ~M-x eval-buffer~.
  - Optionally restart Emacs.

** Structure

- init.el :: Main configuration file.
- early-init.el :: Configurations loaded very early in the startup process.
- custom.el :: Emacs Customization writes to this file. Read-only.
- configs/init-*.el :: Auto-loaded configuration files extracted from init.el
  for better readability.
- Rest of configs/*.el :: Example configuration files, not loaded automatically.
- install-packages.el :: Install configured packages after cloning (on new devices).
- private-init.el :: Private information is stored in this file. Naturally, this
  file is excluded from the repo and loaded only if present in your file system.\\
  For example, =/configs/init-smtp.el= mentions which variables has to be set in
  this file.

